# Generated by Django 4.2 on 2026-06-27 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_expensecategory_sale_purchase_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='butchery',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='butchery',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='served_by',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='products_supplied',
        ),
        migrations.RemoveField(
            model_name='supplierdelivery',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='supplierdelivery',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='dailystock',
            name='sales_quantity',
        ),
        migrations.AddField(
            model_name='dailystock',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailystock',
            name='received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailystock',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_stocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailystock',
            name='closing_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailystock',
            name='date',
            field=models.DateField(default=inventory.models.today),
        ),
        migrations.AlterField(
            model_name='dailystock',
            name='opening_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='CashReconciliation',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='SaleItem',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='SupplierDelivery',
        ),
    ]
