# Generated by Django 4.2 on 2026-07-19 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_alter_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBranchSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=inventory.models.today)),
                ('mpesa_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Staff notes to owner')),
                ('butchery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='inventory.butchery')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('butchery', 'date')},
            },
        ),
    ]
