# Generated by Django 4.2 on 2026-08-29 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_dailybranchsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystock',
            name='transfer_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity transferred to another branch', max_digits=10),
        ),
        migrations.AddField(
            model_name='dailystock',
            name='transfer_to',
            field=models.ForeignKey(blank=True, help_text='Branch to which stock was transferred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_transfers_out', to='inventory.butchery'),
        ),
    ]
