# Generated by Django 4.2 on 2026-08-29 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_dailystock_transfer_quantity_dailystock_transfer_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystock',
            name='transfer_from',
            field=models.ForeignKey(blank=True, help_text='Branch from which stock was received via transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_transfers_in', to='inventory.butchery'),
        ),
        migrations.AlterField(
            model_name='dailystock',
            name='transfer_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity transferred', max_digits=10),
        ),
    ]
