# Generated by Django 4.2 on 2026-08-30 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_dailystock_transfer_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailystock',
            name='transfer_from',
        ),
        migrations.RemoveField(
            model_name='dailystock',
            name='transfer_quantity',
        ),
        migrations.RemoveField(
            model_name='dailystock',
            name='transfer_to',
        ),
        migrations.CreateModel(
            name='DailyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity transferred', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_daily_stock', models.ForeignKey(help_text='The daily stock entry from which stock is transferred', on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='inventory.dailystock')),
                ('to_butchery', models.ForeignKey(help_text='Branch receiving the transfer', on_delete=django.db.models.deletion.CASCADE, related_name='daily_transfers_in', to='inventory.butchery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
