# Generated by Django 4.2 on 2026-09-07 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0008_remove_dailystock_transfer_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date for which permission is granted')),
                ('permission_type', models.CharField(choices=[('EDIT', 'Edit existing data'), ('BACKFILL', 'Add missing data'), ('FULL', 'Full access (edit and backfill)')], default='FULL', max_length=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Reason for granting permission')),
                ('is_active', models.BooleanField(default=True)),
                ('butchery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_permissions', to='inventory.butchery')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-granted_at'],
                'unique_together': {('user', 'butchery', 'date')},
            },
        ),
    ]
