# Generated by Django 4.2 on 2026-09-07 02:51

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_datepermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datepermission',
            options={'ordering': ['-start_date', '-granted_at']},
        ),
        migrations.AlterUniqueTogether(
            name='datepermission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='datepermission',
            name='end_date',
            field=models.DateField(default=inventory.models.today, help_text='End date of the permission range'),
        ),
        migrations.AddField(
            model_name='datepermission',
            name='start_date',
            field=models.DateField(default=inventory.models.today, help_text='Start date of the permission range'),
        ),
        migrations.RemoveField(
            model_name='datepermission',
            name='date',
        ),
    ]
