# Generated by Django 4.2 on 2026-09-07 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0010_alter_datepermission_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date when this price was paid')),
                ('buying_price_per_kg', models.DecimalField(decimal_places=2, help_text='Price per kg from slaughter house', max_digits=10)),
                ('quantity_received', models.DecimalField(decimal_places=2, help_text='Quantity received (in kg)', max_digits=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this purchase')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buying_prices', to='inventory.meatproduct')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_buying_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-recorded_at'],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
