# Generated by Django 4.2.30 on 2026-10-04 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_prices(apps, schema_editor):
    # Original prices at entry time are unknown; current product prices are the best available.
    DailyStock = apps.get_model('inventory', 'DailyStock')
    for row in DailyStock.objects.select_related('product').filter(selling_price__isnull=True):
        row.buying_price = row.product.buying_price
        row.selling_price = row.product.selling_price
        row.save(update_fields=['buying_price', 'selling_price'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0011_buyingprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybranchsummary',
            name='cash_counted',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Physical cash handed over at close of day', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dailybranchsummary',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailybranchsummary',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_days', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailybranchsummary',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailystock',
            name='buying_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dailystock',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RunPython(backfill_prices, migrations.RunPython.noop),
    ]
