# Generated by Django 4.2.30 on 2026-10-09 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inventory.models


def enable_supa(apps, schema_editor):
    apps.get_model('inventory', 'Butchery').objects.filter(name__iexact='Supa').update(serves_schools=True)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0012_daily_price_snapshot_cash_close'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='butchery',
            name='serves_schools',
            field=models.BooleanField(default=False, help_text="Shows the School Deliveries section on this branch's daily entry"),
        ),
        migrations.CreateModel(
            name='SchoolPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Monday of the delivery week this cheque pays for')),
                ('cheque_number', models.CharField(max_length=50)),
                ('bank', models.CharField(blank=True, max_length=100)),
                ('cheque_date', models.DateField(default=inventory.models.today)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_payments', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='inventory.school')),
            ],
            options={
                'ordering': ['-week_start', 'school__name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=inventory.models.today)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_deliveries', to='inventory.meatproduct')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_deliveries', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='inventory.school')),
            ],
            options={
                'verbose_name_plural': 'School deliveries',
                'ordering': ['-date', 'school__name'],
            },
        ),
        migrations.AddField(
            model_name='school',
            name='butchery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='inventory.butchery'),
        ),
        migrations.CreateModel(
            name='SchoolPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_prices', to='inventory.meatproduct')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='inventory.school')),
            ],
            options={
                'unique_together': {('school', 'product')},
            },
        ),
        migrations.RunPython(enable_supa, migrations.RunPython.noop),
    ]
