# Generated by Django 5.2.18 on 2026-10-09 11:32

from datetime import timedelta

from django.db import migrations
from django.utils import timezone


def cap_sessions(apps, schema_editor):
    # Logins created under the old 10-year setting now expire 30 days from today.
    Session = apps.get_model('sessions', 'Session')
    limit = timezone.now() + timedelta(days=30)
    Session.objects.filter(expire_date__gt=limit).update(expire_date=limit)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_schools'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(cap_sessions, migrations.RunPython.noop),
    ]
